packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'packages/mongo-realtime/*'
  # all packages in subdirs of components/
  - 'clones/*'
  # exclude packages that are inside test directories
  - '!**/test/**'